version: "3"

services:
  app:
    build:
      context: "."
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ".:/code"
    env_file: "./postgresql/my_env.env"
    depends_on:
      - db
    command:
      bash -c "/code/wait_for_db.sh &&
      python /code/manage.py runserver 0.0.0.0:8000"
#      /usr/local/bin/uwsgi --http :8000 --wsgi-file /code/Piltover/wsgi.py" # use wsgi settings
  db:
    build:
      context: "./postgresql"
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"
    env_file: "./postgresql/my_env.env"
