version: "3"

services:
  app:
    build:
      context: "."
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ".:/usr/src/app"
    depends_on:
      - db
    command: bash -c "python manage.py migrate | python manage.py runserver 0.0.0.0:8000"
  db:
    build:
      context: "./postgresql"
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"
    env_file: "./postgresql/my_env.env"
