version: "3"

services:
  app:
    build:
      context: "."
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ".:/usr/src/app"
    env_file: "./postgresql/my_env.env"
    depends_on:
      - db
    command:
      bash -c "./wait_for_db.sh |
      python manage.py makemigrations |
      bash -c python manage.py migrate |
      /usr/local/bin/uwsgi --http :8000 --wsgi-file Piltover/wsgi.py"
  db:
    build:
      context: "./postgresql"
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"
    env_file: "./postgresql/my_env.env"
