# Generated by Django 2.2.1 on 2019-09-15 03:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('velkoz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Champion',
            new_name='ChampionModel',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='SkillModel',
        ),
    ]
