# Generated by Django 3.1.2 on 2020-11-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velkoz', '0002_auto_20190915_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='championmodel',
            old_name='range',
            new_name='attack_range',
        ),
        migrations.AlterField(
            model_name='championmodel',
            name='move_speed',
            field=models.IntegerField(default=0),
        ),
    ]
