# Generated by Django 3.1.2 on 2021-01-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velkoz', '0002_auto_20190915_1209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='championmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='skillmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='skillmodel',
            name='patch',
        ),
    ]
