# Generated by Django 3.1.2 on 2020-12-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velkoz', '0003_auto_20201121_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championmodel',
            name='e',
        ),
        migrations.RemoveField(
            model_name='championmodel',
            name='passive',
        ),
        migrations.RemoveField(
            model_name='championmodel',
            name='q',
        ),
        migrations.RemoveField(
            model_name='championmodel',
            name='r',
        ),
        migrations.RemoveField(
            model_name='championmodel',
            name='w',
        ),
    ]
