# Generated by Django 3.1.2 on 2021-01-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velkoz', '0003_auto_20210104_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championmodel',
            name='patch',
        ),
    ]
