# Generated by Django 3.1.2 on 2020-12-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velkoz', '0004_auto_20201206_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championmodel',
            name='patch',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='patch',
            field=models.CharField(max_length=8),
        ),
    ]
