# Generated by Django 3.2.2 on 2021-05-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velkoz', '0004_remove_championmodel_patch'),
        ('velkoz', '0005_auto_20201209_2219'),
    ]

    operations = [
    ]
