# Generated by Django 3.2.2 on 2021-05-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velkoz', '0006_merge_20210527_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='championmodel',
            name='image',
            field=models.ImageField(default=None, upload_to='champion_icon'),
        ),
    ]
